In [27]:
import numpy as np

create

In [28]:
x1 = np.array([2,3,1,5])
print(x1)
print(type(x1))

[2 3 1 5]
<class 'numpy.ndarray'>


In [29]:
x2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(x2)

print(type(x2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [30]:
x3 = np.array([[[1,2,],[3,4]],
               [[5,6],[7,8]]
])
print(x3)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
a  = np.arange(10, 51, 0.5)

print(a)
print(a.shape) # gives the numbers of items in the array

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5 50.  50.5]
(82,)


In [32]:
b = np.linspace(10, 20, 100)
print(b)

[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

In [33]:
c = np.random.randint(-100, 100, (5,5))
print(c)

[[-88 -65  28 -61  92]
 [ 92 -51  71 -35 -47]
 [-89 -36 -24 -95 -59]
 [-68 -77  31  96 -53]
 [-11  34  56  65  95]]


In [34]:
a = np.array([
    [2,4,6],
    [1,3,5],
    ])
b = np.array([
    [1,2],
    [5,1],
    [3,2]
])
print(a, b, sep='\n')
print(a@b)

[[2 4 6]
 [1 3 5]]
[[1 2]
 [5 1]
 [3 2]]
[[40 20]
 [31 15]]


properties

In [35]:
print(a)
print('size')
print(a.size )
print('shape')
print(a.shape)
print('dimention')
print(a.ndim)
print('dtype')
print(a.dtype)

[[2 4 6]
 [1 3 5]]
size
6
shape
(2, 3)
dimention
2
dtype
int32


In [36]:
x = np.random.randint(10,99, (4,5))
print(x)
print(x.reshape(5,4))
print(x.reshape(1,20))
print(x.reshape(20,1))
print(x.reshape(2,10))
print(x.reshape(10,2))


[[71 17 20 76 49]
 [50 71 81 56 46]
 [84 88 55 37 62]
 [56 27 24 37 50]]
[[71 17 20 76]
 [49 50 71 81]
 [56 46 84 88]
 [55 37 62 56]
 [27 24 37 50]]
[[71 17 20 76 49 50 71 81 56 46 84 88 55 37 62 56 27 24 37 50]]
[[71]
 [17]
 [20]
 [76]
 [49]
 [50]
 [71]
 [81]
 [56]
 [46]
 [84]
 [88]
 [55]
 [37]
 [62]
 [56]
 [27]
 [24]
 [37]
 [50]]
[[71 17 20 76 49 50 71 81 56 46]
 [84 88 55 37 62 56 27 24 37 50]]
[[71 17]
 [20 76]
 [49 50]
 [71 81]
 [56 46]
 [84 88]
 [55 37]
 [62 56]
 [27 24]
 [37 50]]


In [37]:
print(x.flatten()) # n dimention array to 1 dimention array

[71 17 20 76 49 50 71 81 56 46 84 88 55 37 62 56 27 24 37 50]


In [38]:
y = np.random.randint(10, 99, (5, 2))
print(y)

[[72 61]
 [50 47]
 [50 97]
 [62 74]
 [60 38]]


In [39]:
y.T

array([[72, 50, 50, 62, 60],
       [61, 47, 97, 74, 38]])

maths and stats

In [40]:
a = np.array([
    [2,4],
    [1,3]
])
b = np.array([
    [1,2],
    [5,1]
])
#addition 
print(a + b)
#subtraction
print(a - b)
# division
print(a / b)
# multiplication
print(a * b)
#dot product
print(a @ b) #matrix multiplication

[[3 6]
 [6 4]]
[[ 1  2]
 [-4  2]]
[[2.  2. ]
 [0.2 3. ]]
[[2 8]
 [5 3]]
[[22  8]
 [16  5]]


In [41]:
print(y)
print(y.sum())  # summation of all elements 
print(y.sum(axis=0)) # summation of each column
print(y.sum(axis=1)) # summation of each row

# mqx and min 
print(y.max(), y.min())
# argmax and argmin -> information about the index of the max and min
print(y.argmax(), y.argmin())

[[72 61]
 [50 47]
 [50 97]
 [62 74]
 [60 38]]
611
[294 317]
[133  97 147 136  98]
97 38
5 9


slicing
  . 1D
x[start:stop:step]

. 2D array
x[rowstart:rowstop:rowstep, colstart:colstop:colstep]

In [42]:
x  =  np.random.randint(10, 100, (10, 10))
print(x)

[[82 70 48 76 31 76 83 66 51 90]
 [87 74 50 88 59 67 51 49 64 52]
 [20 31 13 36 71 70 66 73 98 87]
 [15 62 27 23 65 74 73 90 26 87]
 [31 43 76 52 41 80 39 80 80 35]
 [40 34 19 96 54 61 93 15 81 64]
 [73 52 25 52 11 81 66 90 25 13]
 [48 74 78 30 26 96 33 37 52 46]
 [26 26 74 72 81 30 61 73 44 89]
 [29 16 73 71 97 81 69 16 29 84]]


In [43]:
print(x[0, 0])  #print first item
print(x[-1,-1])   #print last item
print(x[0])  # first row
print(x[-1]) # last row


82
84
[82 70 48 76 31 76 83 66 51 90]
[29 16 73 71 97 81 69 16 29 84]
